module.exports = {
  docs: {
    'Get started': [
      'welcome',
      'offline-access',
      'guide/1-introduction',
      'guide/2-first-test-case',
      'guide/3-actions',
      'guide/4-debugging',
      'guide/5-runtime-params',
      'guide/sql-concept',
    ],
    'Setup': ['ios-setup'],
    'Concepts': ['concepts'],
    'Android setup': ['android-setup'],

    'Guides': [
      // 'how-tos/how-to-create-a-test-case',
      // 'how-tos/how-to-login-to-node',
      'how-tos/guides',
      'how-tos/best-practices',
      'how-tos/zeuz-server-sitemap',
      'how-tos/field-definitions',
      {
        "Testing": [
          'how-tos/how-to-debug-test-cases',
          'how-tos/how-to-deploy-test-cases',
          'how-tos/how-to-create-webhook-for-cicd',
          'how-tos/how-to-generate-execution-report',
          'how-tos/how-to-deploy-and-execute-manual-test-cases',
          'how-tos/how-to-add-runtime-parameters',
          'how-tos/how-to-setup-test-scheduler',
          'how-tos/how-to-create-test-cases',
          'how-tos/how-to-create-folders-and-features',
          'how-tos/how-to-export-and-import-test-cases',
          'how-tos/how-to-move-test-cases-to-folder-and-feature',
          'how-tos/how-to-cancel-a-deploy-run',
          'how-tos/how-to-delete-a-deploy-log',
          'how-tos/how-to-add-actions',
          'how-tos/how-to-copy-and-paste-actions',
          'how-tos/how-to-create-schedule',
          'how-tos/how-to-create-test-plans',
          {
            "Set": [
              'how-tos/how-to-create-test-sets',
              'how-tos/how-to-deploy-test-sets',
              'how-tos/how-to-rearrange-test-cases-in-a-set',
            ],
            "Version": [
              'how-tos/how-to-create-a-branch',
            ],
            "Batch Update": [
              'how-tos/testing/batch-update/test',
            ],
          }
        ],
        "Project": [
          'how-tos/how-to-create-milestones',
          'how-tos/how-to-create-teams',
          'how-tos/how-to-create-projects',
          'how-tos/how-to-link-team-to-a-project',
          'how-tos/how-to-create-requirements',
          'how-tos/how-to-create-tasks',
          'how-tos/how-to-create-bugs',
          'how-tos/how-to-link-items-between-each-other',
          'how-tos/how-to-create-documents',
          'how-tos/how-to-setup-email-notification',
          'how-tos/how-to-create-and-manage-labels',
          'how-tos/how-to-setup-work-schedule',
          'how-tos/how-to-create-templates',
        ],
        "User Management": [
          'how-tos/how-to-create-users',
          'how-tos/how-to-activate-and-deactivate-users',
        ],
        "Admin": [
          'how-tos/how-to-update-actions-from-control-server',
        ],
      },
    ],
    'ZeuZ Node': [
      'zeuz-node',
      'zeuz-node-setup',
      'zeuz-node-usage',
      'variables-and-indexed-access',
      'data-collector',
      'Calling-method-on-variable',
      'loop',
      'element-detection',
      'add-new-actions',
      'custom-driver',
      {
        Actions: [
          'actions-common',
          'actions-web',
          'actions-mobile',
          'actions-rest-api',
          'actions-performance',
          'actions-database',
        ]
      },
      'zeuz-node-changelogs',
    ],
    'ZeuZ Server': [
      'zeuz-server',
      'zeuz-api-examples',
      'zeuz-server-changelogs',
    ],
    'Course': [
      'course-info',
      'course-web',
      // 'course-mobile',
      // 'course-rest-api',
      // 'course-desktop',
    ],
  },
};
