module.exports = {
  docs: {
    "Get started": [
      "welcome",
      "offline-access",
      // "guide/1-introduction",
      // "guide/2-first-test-case",
      // "guide/3-actions",
      // "guide/4-debugging",
      // "guide/5-runtime-params",
    ],
    "AI Test Recorder": [
      "ai-recorder/ai-recorder",
    ],
    "zAI": [
      "zAI/zAI-explain-test-case",
      "zAI/zAI-suggest-step-description-expected",
    ],
    "Guides": [
      // "how-tos/how-to-create-a-test-case",
      // "how-tos/how-to-login-to-node",
      "how-tos/guides",
      "how-tos/best-practices",
      "how-tos/zeuz-server-sitemap",
      "how-tos/field-definitions",
      {
        "Testing": [
          "how-tos/how-to-debug-test-cases",
          "how-tos/how-to-deploy-test-cases",
          "how-tos/how-to-create-webhook-for-cicd",
          "how-tos/how-to-generate-execution-report",
          "how-tos/how-to-deploy-and-execute-manual-test-cases",
          "how-tos/how-to-add-runtime-parameters",
          "how-tos/how-to-setup-test-scheduler",
          "how-tos/how-to-create-test-cases",
          "how-tos/how-to-create-folders-and-features",
          "how-tos/how-to-export-and-import-test-cases",
          "how-tos/how-to-move-test-cases-to-folder-and-feature",
          "how-tos/how-to-cancel-a-deploy-run",
          "how-tos/how-to-delete-a-deploy-log",
          "how-tos/how-to-add-actions",
          "how-tos/how-to-copy-and-paste-actions",
          "how-tos/how-to-create-schedule",
          "how-tos/how-to-create-test-plans",
          "how-tos/how-to-use-history-page",
          {
            "Set": [
              "how-tos/how-to-create-test-sets",
              "how-tos/how-to-deploy-test-sets",
              "how-tos/how-to-rearrange-test-cases-in-a-set",
            ],


            "Batch Update": [
              "how-tos/testing/batch-update/test",
            ],
          }
        ],
        "Project": [
          "how-tos/how-to-create-milestones",
          "how-tos/how-to-create-teams",
          "how-tos/how-to-create-projects",
          "how-tos/how-to-link-team-to-a-project",
          "how-tos/how-to-create-requirements",
          "how-tos/how-to-create-tasks",
          "how-tos/how-to-create-bugs",
          "how-tos/how-to-link-items-between-each-other",
          "how-tos/how-to-create-documents",
          "how-tos/how-to-setup-email-notification",
          "how-tos/how-to-create-and-manage-labels",
          "how-tos/how-to-setup-work-schedule",
          "how-tos/how-to-create-templates",
          "how-tos/how-to-use-version-page",
          "how-tos/how-to-create-a-worklog",
        ],
        "User Management": [
          "how-tos/how-to-create-users",
          "how-tos/how-to-activate-and-deactivate-users",
        ],
        "Admin": [
          "how-tos/admin/how-to-update-actions-from-control-server",
          "how-tos/admin/how-to-use-accounts-log",
          {
            "SSO": [
              "how-tos/admin/sso/sso-microsoft-entra-id",
            ]
          }
        ],
      },
    ],
    "ZeuZ Node": [
      "zeuz-node",
      "ip-url-whitelist",
      "how-tos/easy-ocr-installation",
      "zeuz-node-setup",
      "android-setup",
      "ios-setup",
      "zeuz-node-usage",
      "variables-and-indexed-access",
      "data-collector",
      "Calling-method-on-variable",
      "loop",
      "element-detection",
      "add-new-actions",
      "custom-driver",
      {
        Actions: [
          {
            "Web": [
              "actions-web",
              "actions/web/go-to-link",
              "actions/web/save-and-read-mail-action",
              "actions/web/handle-alert",
              "actions/web/keystroke-chars",
              "actions/web/navigate-back",
              "actions/web/navigate-forward",
              "actions/web/navigate-refresh",
              "actions/web/select-element-by-index",
              "actions/web/select-element-by-value",
              "actions/web/switch-browser-window-tab",
              "actions/web/upload-a-file",
              "actions/web/deselect-element-by-index",
              "actions/web/start-timer",
              "actions/web/click-and-hold-an-element",
              "actions/web/select-visible-text-with-siblings",
              "actions/web/check-or-uncheck-all-elements",
              "actions/web/check-or-uncheck-multiple-elements",
              "actions/web/close-tab",
              "actions/web/context-click-right-mouse-click",
              "actions/web/deselect-all",
              "actions/web/change-attribute-value",
              "actions/web/scroll-to-an-element",
              "actions/web/switch-iframe",
              "actions/web/teardown-web-browser",
              "actions/web/take-screenshot",
              "actions/web/click-an-element",
              "actions/web/click-and-download-attachments",
              "actions/web/go-to-webpage",
              "actions/web/enter-text",
              "actions/web/if-an-item-is-found-or-not",
              "actions/web/save-attribute-values-in-list",
              "actions/web/save-attribute-value",
              "actions/web/select-by-visible-text",
              "actions/web/validate-exact-text",
              "actions/web/validate-partial-text",
              "actions/web/wait-for-an-element-to-appear",
              "actions/web/wait-for-an-element-to-disappear",
              "actions/web/check-or-uncheck-single-element",
              "actions/web/double-click-an-element",
              "actions/web/extract-table-data",
              "actions/web/hover-over-an-element",
              "actions/web/open-a-new-tab",
              "actions/web/save-and-get-element",
              "actions/web/save-text",
              "actions/web/save-web-elements-in-list",
              "actions/web/switch-browser"

            ],
            "Common": [
              "actions-common",
              "actions/common/proxy-server",
              "actions/common/wait-for-timer"
            ],
            "Mac": [
              "actions-mac",
              "actions/mac/click-an-element",
              "actions/mac/enter-text"
            ],
            "GUI controls": [
              "actions/gui-controls/action-gui-controls-ocr-get-text-using-image",
              "actions/gui-controls/action-gui-controls-ocr-get-text-using-text",
              "actions/gui-controls/action-gui-controls-ocr-get-text-using-coords",
              "actions/gui-controls/actions-gui",
            ],
            "AI actions": [
              "actions/ai-actions/ai-actions",
              "actions/ai-actions/openai-action",
              "actions/ai-actions/example-of-openai-action",
            ],
          },
          "actions-mobile",
          // "actions-desktop",
          "actions-rest-api",
          "actions-performance",
          "actions-database",
          "actions-windows",
          "actions-security",
        ]
      },
      "zeuz-node-changelogs",
    ],
    "ZeuZ Server": [
      "zeuz-server",
      "zeuz-api-examples",
      "zeuz-server-changelogs",
    ],
    "Concepts": [
      "concepts",
      "zeuz-features",
      "sql-concept",
      "software-lifecycle-model",
    ],
    "Course": [
      "course-info",
      "course-web",
      // "course-mobile",
      // "course-rest-api",
      // "course-desktop",
    ],
  },
};
